from modelado.modelado import *

jugador1 = Futbolista()
equipo1 = Equipo()
jugador2 = Futbolista()
equipo2 = Equipo()
jugador3 = Futbolista()
equipo3 = Equipo()

equipo1.set_nombreq("Manchester United")
equipo1.set_pais("Inglaterra")
jugador1.set_nombre("Antonio")
jugador1.set_apellido("Valencia")
jugador1.set_equipo(equipo1)
jugador1.set_posicion("Lateral")
jugador1.set_dorsal(7)
print(jugador1.presentar_datos())

equipo2.set_nombreq("Nexaca")
equipo2.set_pais("Mexico")
jugador2.set_nombre("Alex")
jugador2.set_apellido("Aguinaga")
jugador2.set_equipo(equipo2)
jugador2.set_posicion("MEDIOCENTRO")
jugador2.set_dorsal(7)
print(jugador2.presentar_datos())

equipo3.set_nombreq("Lazio")
equipo3.set_pais("Italia")
jugador3.set_nombre("Felipe")
jugador3.set_apellido("Caicedo")
jugador3.set_equipo(equipo3)
jugador3.set_posicion("Delantero")
jugador3.set_dorsal(9)
print(jugador3.presentar_datos())
