from modelado.modelo import *
g1 = Garante()
g1.set_nombre("Pedro")
g1.set_apellido("Sanchez")
g1.set_sueldo(1000)
g2 = Garante()
g2.set_nombre("Carlos")
g2.set_apellido("Armijos")
g2.set_sueldo(199)
prestamo = Prestamo()
prestamoauto = PrestamosAutomovil()
prestamo.setnombre_beneficiario("Juan")
prestamo.set_sueldo(1000)
prestamo.setmonto_prestamo(100000)
prestamo.set_interes(15)
prestamo.set_tiempo(5)
prestamo.set_garante1(g1)
print(prestamo.presentar_datos())
prestamoauto.setnombre_beneficiario("Jose")
prestamoauto.set_sueldo(1000)
prestamoauto.setmonto_prestamo(30200)
prestamoauto.set_interes(15)
prestamoauto.set_tiempo(5)
prestamoauto.set_garante1(g2)
prestamoauto.set_tipo_vehiculo("auto")
prestamoauto.set_marca_vehiculo("Mazda")
prestamoauto.set_garante2(g1)
print(prestamoauto.presentar_datos())
